//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircleSearch.Overlay.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CircleSearch.Overlay.Resources.Locales.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action_close_tooltip.
        /// </summary>
        internal static string action_close_tooltip {
            get {
                return ResourceManager.GetString("action_close_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action_doc_id_title.
        /// </summary>
        internal static string action_doc_id_title {
            get {
                return ResourceManager.GetString("action_doc_id_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action_image_search_title.
        /// </summary>
        internal static string action_image_search_title {
            get {
                return ResourceManager.GetString("action_image_search_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action_image_search_tooltip.
        /// </summary>
        internal static string action_image_search_tooltip {
            get {
                return ResourceManager.GetString("action_image_search_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action_search_title.
        /// </summary>
        internal static string action_search_title {
            get {
                return ResourceManager.GetString("action_search_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action_search_tooltip.
        /// </summary>
        internal static string action_search_tooltip {
            get {
                return ResourceManager.GetString("action_search_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action_text_copy_title.
        /// </summary>
        internal static string action_text_copy_title {
            get {
                return ResourceManager.GetString("action_text_copy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action_text_copy_tooltip.
        /// </summary>
        internal static string action_text_copy_tooltip {
            get {
                return ResourceManager.GetString("action_text_copy_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action_translate_title.
        /// </summary>
        internal static string action_translate_title {
            get {
                return ResourceManager.GetString("action_translate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action_translate_tooltip.
        /// </summary>
        internal static string action_translate_tooltip {
            get {
                return ResourceManager.GetString("action_translate_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overlay_draw_circle_title.
        /// </summary>
        internal static string overlay_draw_circle_title {
            get {
                return ResourceManager.GetString("overlay_draw_circle_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overlay_press_esc_title.
        /// </summary>
        internal static string overlay_press_esc_title {
            get {
                return ResourceManager.GetString("overlay_press_esc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overlay_processing_title.
        /// </summary>
        internal static string overlay_processing_title {
            get {
                return ResourceManager.GetString("overlay_processing_title", resourceCulture);
            }
        }
    }
}
