global using CommunityToolkit.Mvvm.ComponentModel;
global using CircleSearch.Tray.ViewModels;
global using ThemeType = Wpf.Ui.Appearance.ApplicationTheme;
global using Watcher = Wpf.Ui.Appearance.SystemThemeWatcher;
global using System.Windows;
global using Wpf.Ui.Appearance;
global using CircleSearch.Tray.Utils;
global using CircleSearch.Tray.Views;
global using CircleSearch.Tray.Services;
global using System.ComponentModel;
global using Wpf.Ui.Abstractions.Controls;
global using CommunityToolkit.Mvvm.Input;
global using System.Collections.ObjectModel;
global using CircleSearch.CFS;
global using Wpf.Ui.Controls;
global using CircleSearch.Tray.Resources;
global using System.Security.Cryptography;
global using System.Text;
global using System.Globalization;
global using System.Resources;
global using System.Windows.Data;
global using CircleSearch.Tray.Models;
global using System.IO;
global using System.Text.Json;